### ISSUE TITLE
Error since composer update

### ISSUE THREAD

**Issue by timtailor** [widop/WidopHttpAdapterBundle#19] opened 2014-08-04 20:59 UTC
Since a recent upgrade i am getting the following error in the egeloen/ivory-google-map Bundle (DistanceMatrix)
It seems to be caused by widop/http-adapter 1.1.0 (when i copy the old version of widop/http-adapter it is working)

Does anyone else have problems as well?

Error message:

Warning: json_decode() expects parameter 1 to be string, object given in myproject\vendor\egeloen\google-map\src\Ivory\GoogleMap\Services\DistanceMatrix\DistanceMatrix.php line 175

**Comment by egeloen** [comment] 2014-08-04 21:39
Closing as it is not related to this repository.

**Closed as completed by egeloen** 2014-08-04 21:39 UTC

**Comment by mrychlik** [comment] 2014-08-05 00:53
The problem is real and is due to a change in the type of the return value
of the widop/http-adapter which happened in version 1.1. Unfortunately,
going back to version 1.0 does not work either. I made changes which seem
to fix the problem. See my forks:
https://github.com/mrychlik

**Comment by mrychlik** [comment] 2014-08-05 01:05
PS: To get the fix, you would need to use my forked versions at
https://github.com/mrychlik
The version dev-widop12 works for me. I am using the following bits in my
composer.json:

```
"repositories": [
```

....
{
    "type": "vcs",
    "url":  "https://github.com/mrychlik/ivory-google-map.git"
},
{
    "type": "vcs",
    "url":  "https://github.com/mrychlik/IvoryGoogleMapBundle.git"
}
    ]
 "require": {
       ....
        "egeloen/google-map": "dev-widop12@dev",
        "egeloen/google-map-bundle": "dev-widop12@dev"
       ...
}
Best,
--Marek Rychlik

**Comment by egeloen** [comment] 2014-08-05 02:13
@mrychlik I know there is a BC break between `1.0.x` to `1.1.x` which now returns a response object instead of the plain response body as document in the `UPGRADE` file. Anyway, saying that downgrading to `1.0.x` does not work is wrong as it works perfectly. Maybe you're confusing the bundle and the library because if you downgrade the `widop/http-adapter-bundle` to `1.0.x` instead of the `widop/http-adapter` library, then it will not work (the BC break is not in the bundle but in the library and installing the bundle as `1.0.x` will install the `1.1.x` library).

**Comment by mrychlik** [comment] 2014-08-05 03:09
The reason why the downgrade to 1.0.x did not work was that
egeloen/google-map now uses Widop\HttpAdapter\HttpAdapterInterface
but widop/http-adapter has no idea what that is before version 1.1.
I am recalling from memory on something I did two weeks ago or so, so this
eeds checking. In any case, assuming that version 1.1 is better, would it
not be better to make the new software use it?
Best regards,
--Marek Rychlik

**Comment by egeloen** [comment] 2014-08-05 12:35
That's strange because the interface is part of the library since the 1.0.0 (See https://github.com/widop/http-adapter/blob/1.0.0/src/Widop/HttpAdapter/HttpAdapterInterface.php). Anyway, updating the google map library in order to use the `1.1.x` release is the way to go.

**Comment by timtailor** [comment] 2014-08-05 17:36
The fix mentioned by egeloen mentioned here https://github.com/egeloen/IvoryGoogleMapBundle/issues/119 works for me!
