### ISSUE TITLE
Buzz file_get_contents error

### ISSUE THREAD

**Issue by fabstei** [widop/WidopHttpAdapterBundle#3] opened 2012-11-06 17:22 UTC
The Buzz Adapter seems broken. Using it, all calls end in an

```
 file_get_contents(https://accounts.google.com/o/oauth2/token):
 failed to open stream: operation failed 
```

error.

**Comment by clemherreman** [comment] 2012-11-08 13:36
Please check that the value of `allow_url_fopen` in your php configuration is set to `true`.

Also, your url returns a `405 - Method Not Allowed`, which might be the cause of the error message.

**Comment by fabstei** [comment] 2012-11-08 14:08
allow_url_fopen is set to true (and file_get_contents works without problems in other contexts).

The above mentioned error occurs while trying to use the authentication example provided in the Readme of widop/google-analytics-bundle. 

Switching to the curl adapter did the trick for me, so I didn't investigate the error any further.

**Comment by clemherreman** [comment] 2012-11-08 15:21
Closing this at it smells like a Buzz issue.

**Closed as completed by clemherreman** 2012-11-08 15:21 UTC

**Comment by clemherreman** [comment] 2012-11-09 09:23
@fabstei Seems that `file_get_content` doesn't support https requests. See https://github.com/kriswallsmith/Buzz/issues/67
